namePrefix: prod-
commonLabels:
  owner: hwchiu
#bases:
resources:
  - ../../base
patches:
#  - replica_count.yaml
  - path: replica_count.yaml
configMapGenerator:
  - name: ks-config
    files:
      - test.config
